name: release

on:
  release:
    types: [released]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy-oss

      - name: Tag image with version
        run: docker image tag palcode/runner palcode/runner:${{ GITHUB_REF }}
