name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Compile TypeScript
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - uses: olegtarasov/get-tag@v2
        id: tagName
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: palcode/runner:${{ steps.tagName.outputs.tag }}
